apiVersion: v1
kind: Secret
metadata:
  name: redis-connection
  namespace: shop
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: shop
type: Opaque
stringData:
  PODINFO_CACHE_SERVER: "tcp://redis.shop.svc.cluster.local:6379"
